python label2vec.py \
--train_path     ./xmc-base/wiki-500k/Y.trn.txt \
--save_path    ./xmc-base/wiki-500k/label_embed.npy \
--mode         1 \
--sample       0.1 \
--ns_exponent  -1.0 \
--alpha        2.5e-2 \
--alpha_min    1e-4  \
--emb_size     100 \
--negative     20  \
--epochs       50  \
--win_size     274  \
--seed         1   \
--num_label    501070
